import type { ITestimonial } from "../types";

export const testimonialsData: ITestimonial[] = [
  {
    image:
      "https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=200",
    name: "Aarav Mehta",
    handle: "@aaravcreates",
    date: "February 14, 2025",
    quote:
      "Clickloom helped me cut thumbnail design time drastically. I can now focus more on content instead of struggling with layouts and colors.",
  },
  {
    image:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200",
    name: "Meera Shah",
    handle: "@meeramarkets",
    date: "March 3, 2025",
    quote:
      "The thumbnails generated by Clickloom stand out immediately. The AI clearly understands contrast and attention better than most tools I’ve tried.",
  },
  {
    image:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200&auto=format&fit=crop&q=60",
    name: "Rohit Verma",
    handle: "@rohitbuilds",
    date: "April 22, 2025",
    quote:
      "I’m not a designer, but Clickloom makes thumbnail creation feel effortless. The customization options are simple yet powerful.",
  },
  {
    image:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=60",
    name: "Neha Kapoor",
    handle: "@neha_creates",
    date: "May 18, 2025",
    quote:
      "From idea to thumbnail in minutes. Clickloom fits perfectly into my workflow and saves me hours every week.",
  },
];
